@startuml

left to right direction

actor Developer as developer
actor "Device Owner" as DevOwn
package Junknet { 
	usecase (Initiate a Job) as initiate
	usecase (Cancel Job) as cancel
        usecase (Start Daemon) as start
        usecase (Stop Daemon) as stop

}

developer --> initiate
developer --> cancel
DevOwn --> start
DevOwn --> stop
@enduml
